[paths]
old_upload = "./data/upload"
old_edited = "./data/edit"

upload = "/workspaces/ai-butlerhat/data-butlerhat/robotframework-butlerhat/TestSuites/Crawl/data/upload"
edited = "/workspaces/ai-butlerhat/data-butlerhat/robotframework-butlerhat/TestSuites/Crawl/data/edit"
rpa_dataset = "/workspaces/ai-butlerhat/data-butlerhat/robotframework-butlerhat/TestSuites/Crawl/data/rpa_dataset"

to_alfred = "./data/"

to_buibert = "./data/to_buibert"
logo = "./static/logo.png"
buibert_tokenizer = "./buibert/static/uncased_L-4_H-512_A-8_tokenizer.json"

[configs]
new_task_id_offset = 100000

[urls]
ocr = "http://nginx:80"

[theme]
base="dark"
primaryColor="#ffbd63"
backgroundColor="#000000"
secondaryBackgroundColor="#3f4a65"

[browser]
gatherUsageStats = false