[paths]

base_dir = "/workspaces/ai-butlerhat/ai-butlerhat-projects"
upload = "upload/"
edited = "edit/"
rpa_dataset = "rpa_dataset/"
pretraining_dataset = "pretraining_dataset/"
trained = "trained"
tested = "tested"

base_model = "/workspaces/ai-butlerhat/model/ciclozero"
hf_cache = "/workspaces/ai-butlerhat/.hf_cache/transformers"
default_training_json = "/workspaces/ai-butlerhat/scripts/default_train_config.json"

logo = "./web/static/logo.png"

[configs]
new_task_id_offset = 100000

[urls]
ocr = "http://nginx_alfred:80/fd/ppocrv3"

[theme]
base="dark"
primaryColor="#00ff9c"
backgroundColor="#333333"
secondaryBackgroundColor="#000000"

[browser]
gatherUsageStats = false