name: web_env

channels:
  - default
  - conda-forge

dependencies:
  - python=3.10
  - nodejs
  - pip

  - pip:
    - transformers[torch]==4.30.2
    - torchvision
    - timm
    - sentencepiece
    - wandb
    - evaluate
    - nltk
    - pytorch-lightning
    - absl-py
    - rouge-score
    # - fastdeploy-python  # fastdeploy is not supported in python 3.11 yet
    - streamlit
    - streamlit-option-menu
    - streamlit-vis-timeline
    - tqdm
    - Pillow
    - datasets
    - pandas
    - robotframework==6.1.1
    - robotframework-butlerhat[browser_stealth]
    - stqdm
    - openai
    # Interpreter
    - git+https://github.com/robocorp/robotframework-lsp.git@release-robotframework-lsp#subdirectory=robotframework-interactive/src
    - git+https://github.com/robocorp/robotframework-lsp.git@release-robotframework-lsp#subdirectory=robocorp-python-ls-core/src
    - pydantic-settings
    - python-multipart